[package]
name = "nex_ui_native"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
winit = "0.30"
wgpu = "23"
cosmic-text = "0.12"
taffy = "0.5"
crossterm = "0.28"
pollster = "0.4"
