[package]
name = "nexc_codegen_llvm_jit"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nexc_diag = { path = "../nexc_diag" }
nexc_ir = { path = "../nexc_ir" }

